version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    container_name: woowa-elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./dict:/usr/share/elasticsearch/config/dict
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    command: /bin/sh -c "./bin/elasticsearch-plugin install analysis-nori; /usr/local/bin/docker-entrypoint.sh"